
%  dithering_refactored.m
%  Reflected-seismic-pulse / dithering simulation (refactored).
%
%  Structure (top to bottom):
%    1. PARAMETERS  - every configurable number lives here, no globals
%    2. SETUP       - build x, noise, dither once
%    3. MAIN LOOP   - per impulse: analyse, report, plot
%    4. FUNCTIONS   - makeSums, analyzeSignal, analyzeDithered,
%                     reportSignal, plotStep (+ small helpers)
%
%  The three signal variants (unnoised / noised / dithered) are no longer
%  carried as *_unn / *_noi / *_dit suffixed variables. Each is one struct
%  produced by analyzeSignal, so a struct field like  unn.fzero_x  replaces
%  the old  fzero_min_X_Pol_unn,  and the giant multi-output signatures are
%  gone.
%
%  NOTE on preserved behaviours (see the chat notes for details):
%   (a) sumNoi adds `noise` to each pulse, so the noise term appears twice.
%   (b) With params.dithRegen = false (default, = your original), the dither
%       array is fixed, so all params.nDith realizations are identical and
%       the "averaging" returns that single value. Set dithRegen = true for
%       genuine per-realization (Monte-Carlo) dithering.
%   (c) All three variants now take derivatives of the *normalized* polynomial
%       (the original normalized the dithered poly only after differentiating,
%       putting its diff curves on a different vertical scale).
% =====================================================================

clear; clc; 

%% 1. PARAMETERS ------------------------------------------------------
params.dt           = 0.5;    % step of the moving pulse
params.fixedPos     = 5;      % position of the fixed pulse: sech(x - fixedPos)
params.fragMargin   = 1.5;    % fragment half-padding (x-units) added beyond
                              % each of the two detected peaks (replaces the
                              % old amplitude cut-off params.ampThreshold)
params.polyDeg      = 7;      % polynomial degree for all three fits
params.noiseAmp     = 0.20;   % noise amplitude (was a1)

% --- dither (Δ-referenced, per Lipshitz/Wannamaker/Vanderkooy 1992) ---
%  The dither amplitude is tied to the quantizer step Δ, NOT to noiseAmp.
%  Canonical non-subtractive forms generated by makeDither():
%    'rpdf'  : Δ·(rand−0.5)        1Δ p-p, σ=Δ/√12 — mean-linearising only
%    'tpdf'  : Δ·(rand+rand−1)     2Δ p-p, σ=Δ/√6  — best scientific choice:
%              decouples error mean AND variance from the signal at minimum
%              added power (Wannamaker's theorem)
%    'gauss' : (Δ/2)·randn         σ=Δ/2 — also linearises, more power, tails
params.dithPDF      = 'tpdf';
params.subtractive  = false;  % true = subtractive dithering: the recovery side
                              % knows d and removes it after quantization
                              % (Schuchman 1964). Optimal PDF is then RPDF of
                              % exactly 1Δ; total error = U(−Δ/2,Δ/2), power
                              % Δ²/12. Physically requires the dither sequence
                              % to be stored/transmitted with the record.
                              % (The sweep always runs BOTH modes for overlay.)
params.quantizeMain = true;   % true = main loop quantizes sumNoi+dither with
                              % step Δ, so the dither theorems actually apply;
                              % false = old behaviour (dither as plain noise)
params.nDith        = 100;    % number of dithering realizations
params.impulses     = 4;      % which impulse steps to run (e.g. 1:8)

params.dithRegen    = true;  % false = original behaviour; true = real dithering
params.seed         = [];     % fixed RNG seed for reproducible runs; [] = random
params.saveResults  = false;  % true -> save results+params to a .mat file

% --- dither-PDF linearisation sweep (optional) ---
params.runDitherSweep = true;               % run the dither-PDF sweep after the main loop
params.sweepImpulse  = params.impulses(1); % which impulse to analyse
params.quantFrac         = 0.25;  % quantizer step Δ as a fraction of max(sumUnn);
                                  % LARGER = coarser quantizer = larger sub-LSB recovery task
params.sweepSigmaMax        = 1.5;   % sweep noise σ up to this multiple of Δ
params.sweepNumSigma        = 25;    % number of σ points in the sweep
params.sweepNumAvg          = 100;   % N: dithered copies averaged per position estimate
params.sweepNumRepeat       = 40;    % M: independent repeats per σ (for the statistics)
params.measNoiseSigma      = 0;     % your measurement-noise std, for the σ_d recommendation

% --- smooth, earth-media (mostly harmonic) measurement-noise model ---
%  Replaces the white  noiseAmp*(rand-0.5)  on the trace. Noise is built as a
%  band-limited harmonic superposition, so it has no energy near the spatial
%  Nyquist and is therefore smooth. (Spatial frequencies are in cycles per
%  x-unit; your grid's Nyquist is ~1/(2·dx) ≈ 67, so all of these are well
%  below it.)
params.seisNb   = 60;     % # of components in the ambient "microseism" band
params.seisK0   = 2.0;    % band centre frequency   [cycles per x-unit]
params.seisBW   = 0.8;    % band half-width         [cycles per x-unit]
params.seisKc   = 1.2;    % fundamental of the discrete harmonic (cultural) lines
params.seisHarm = 4;      % # of discrete harmonics (kc, 2kc, ... )
params.wBand    = 1.0;    % mix weight: ambient microseism band
params.wLines   = 0.4;    % mix weight: discrete harmonic lines
params.wRed     = 0.3;    % mix weight: red (visco-elastic) background
params.noiseRMS = [];     % [] => match old uniform-noise RMS (noiseAmp/sqrt(12))

%% 2. SETUP -----------------------------------------------------------
left_x = -5; right_x = 10; n_points = 2002;
x = linspace(left_x, right_x, n_points);

if ~isempty(params.seed)
    rng(params.seed);
end
% Smooth, earth-media-induced noise on each pulse's trace (two independent
% realizations). See makeSeismicNoise below.
noise1 = makeSeismicNoise(x, params);
noise2 = makeSeismicNoise(x, params);
noise  = noise1;          % back-compat alias (makeSums now uses noise1/noise2)

% Dither stays WHITE on purpose: RPDF/TPDF dither must be broadband to
% linearise the quantiser (Lipshitz/Vanderkooy). Do NOT smooth this one.
% It is now generated inside analyzeDithered (per realization, Δ-referenced),
% because Δ = quantFrac·max(sumUnn) is only known per impulse.

%% 3. MAIN LOOP -------------------------------------------------------
results = struct([]);
k = 0;
for i_nImp = params.impulses

    [sumUnn, sumNoi] = makeSums(x, i_nImp, params, noise1, noise2);

    % fragment mask: single source of truth, built from the clean sum.
    % Peak-bracket criterion (replaces the amplitude cut).
    mask = peakBracketMask(x, sumUnn, params);

    unn = analyzeSignal(x, sumUnn, mask, params.polyDeg);
    noi = analyzeSignal(x, sumNoi, mask, params.polyDeg);

    Delta = params.quantFrac * max(sumUnn);   % quantizer step for this impulse
    dit = analyzeDithered(x, sumNoi, mask, params.polyDeg, params.nDith, ...
                          params.dithRegen, Delta, params.dithPDF, ...
                          params.quantizeMain, params.subtractive);

    k = k + 1;
    results(k).i_nImp = i_nImp;
    results(k).unn    = unn;
    results(k).noi    = noi;
    results(k).dit    = dit;

    reportSignal(i_nImp, unn, noi, dit);
    plotStep(i_nImp, x, sumUnn, unn, noi, dit);
end

%% 3b. DITHER-PDF LINEARISATION SWEEP (optional) ----------------------
%  Compares RPDF / TPDF / Gaussian non-subtractive dither at equal RMS:
%  dither added before the coarse quantizer, averaged over N realizations,
%  recovers the sub-LSB pulse position. Each curve dips (or flattens) at
%  its linearisation optimum.
if params.runDitherSweep
    iSweep = params.sweepImpulse;
    sumUnnSweep = makeSums(x, iSweep, params, noise1, noise2);
    maskSweep   = peakBracketMask(x, sumUnnSweep, params);

    sw = sweepDitherPDF(x, sumUnnSweep, maskSweep, params);
    plotDitherSweep(sw, iSweep);

    fprintf('\n--- Dither-PDF linearisation sweep (impulse %d) ---\n', iSweep);
    fprintf(' quantizer step Δ        = %.6f\n', sw.Delta);
    fprintf(' clean (true) position   = %.6f\n', sw.x_true);
    fprintf(' RMSE at σ = 0 (no dith) = %.6f\n', sw.rmse(1, 1, 1));
    for mode = 1:2
        fprintf(' [%s]\n', sw.modes{mode});
        for ip = 1:numel(sw.pdfs)
            [mn, iStar] = min(sw.rmse(ip, :, mode));
            fprintf('  %-5s: empirical σ* = %.6f (%.3f·Δ), min RMSE = %.6f\n', ...
                    upper(sw.pdfs{ip}), sw.sigma(iStar), ...
                    sw.sigma(iStar)/sw.Delta, mn);
        end
    end
    fprintf(' canonical points: RPDF %.3f·Δ (subtractive optimum, Schuchman), ', ...
            sw.sigmaCanon(1)/sw.Delta);
    fprintf('TPDF %.3f·Δ (non-subtractive optimum), Gauss %.3f·Δ\n', ...
            sw.sigmaCanon(2)/sw.Delta, sw.sigmaCanon(3)/sw.Delta);

    % dither budget: TPDF canonical point, after subtracting measured noise
    sigma_d = ditherBudget(sw.sigmaCanon(2), params.measNoiseSigma);
    fprintf(' recommended TPDF dither σ_d = %.6f  (for measured σ_n = %.6f)\n', ...
            sigma_d, params.measNoiseSigma);
end

if params.saveResults
    save('dithering_results.mat', 'results', 'params');
end

fprintf('\n--Конец программы--\n');


% =====================================================================
%%  4. FUNCTIONS
% =====================================================================

% ---------------------------------------------------------------------
%  Build the moving + fixed pulses and their sums.
% ---------------------------------------------------------------------
function [sumUnn, sumNoi] = makeSums(x, i_nImp, params, noise1, noise2)
    imp_n        = sech(x - i_nImp * params.dt);   % moving pulse
    imp_constant = sech(x - params.fixedPos);      % fixed pulse

    sumUnn = imp_n + imp_constant;

    % Original adds `noise` to EACH pulse before summing, so the noise term
    % ends up in the sum twice (sumNoi = sumUnn + 2*noise). Preserved as-is.
    sumNoi = (imp_n + noise1) + (imp_constant + noise2);
end

% ---------------------------------------------------------------------
%  Fragment selector (replaces the amplitude cut).
%  The fragment is the span between the two dominant peaks of the clean
%  sum, padded by params.fragMargin on each side. If only one peak exists
%  (pulses merged) it returns a symmetric window around that peak, so the
%  downstream fit still has data but analyzeSignal will report no valley.
% ---------------------------------------------------------------------
function mask = peakBracketMask(x, sig, params)
    maxTF = islocalmax(sig, 'MaxNumExtrema', 2, 'SamplePoints', x);
    xPk   = sort(x(maxTF));
    if numel(xPk) >= 2
        lo = xPk(1)   - params.fragMargin;
        hi = xPk(end) + params.fragMargin;
    else
        if isempty(xPk), [~, im] = max(sig); xPk = x(im); end
        lo = xPk(1) - params.fragMargin;
        hi = xPk(1) + params.fragMargin;
    end
    mask = x >= lo & x <= hi;
end

% ---------------------------------------------------------------------
%  Smooth, earth-media-induced (mostly harmonic) seismic noise.
%  n(x) = ambient microseism band  +  discrete harmonic lines  +  red
%  visco-elastic background. Everything is a sum of sinusoids, band-limited
%  well below the spatial Nyquist, so the trace is smooth (unlike rand).
%  Toolbox-free. Returns a 1×N row vector whose RMS matches the old uniform
%  noise (= noiseAmp/sqrt(12)) unless params.noiseRMS is set.
% ---------------------------------------------------------------------
function n = makeSeismicNoise(x, params)
    x = x(:).';  N = numel(x);

    % 1. ambient microseism band: dense harmonics under a Gaussian envelope
    kb = abs(params.seisK0 + params.seisBW * randn(1, params.seisNb));
    ab = exp(-((kb - params.seisK0) ./ params.seisBW).^2);   % spectral shape
    ph = 2*pi * rand(1, params.seisNb);
    band = sum( ab(:) .* sin(2*pi * kb(:) .* x + ph(:)), 1 );

    % 2. discrete harmonic (cultural / normal-mode) lines: kc, 2kc, ...
    lines = zeros(1, N);
    for h = 1:params.seisHarm
        lines = lines + (1/h) * sin(2*pi * (h*params.seisKc) .* x + 2*pi*rand);
    end

    % 3. red background (visco-elastic medium acts as a low-pass), 1/k^2
    Nr = 24;
    kr = (1:Nr) * (params.seisK0 / Nr);
    ar = 1 ./ (kr.^2);
    red = sum( ar(:) .* sin(2*pi * kr(:) .* x + 2*pi*rand(Nr,1)), 1 );

    % mix, de-mean, match RMS
    n = params.wBand*band + params.wLines*lines + params.wRed*red;
    n = n - mean(n);
    if isfield(params,'noiseRMS') && ~isempty(params.noiseRMS)
        target = params.noiseRMS;
    else
        target = params.noiseAmp / sqrt(12);   % RMS of the old uniform noise
    end
    n = target * n / std(n);
end

% ---------------------------------------------------------------------
%  Analyse ONE signal: fragment, polynomial fit, derivatives, extrema,
%  and the exact derivative-zero (polynomial minimum). Returns a struct.
%  Replaces getPol + getDiffSumAndPol + get_Inflection_Points_And_Zeros
%  for a single signal.
% ---------------------------------------------------------------------
function s = analyzeSignal(x, sig, mask, polyDeg, opts)
    arguments
        x       (1,:) double
        sig     (1,:) double
        mask    (1,:) logical
        polyDeg (1,1) double
        opts.Normalize (1,1) logical = true
    end

    s.x_frag   = x(mask);
    s.sig_frag = sig(mask);

    ext = {'MaxNumExtrema', 1, 'ProminenceWindow', [3 4], 'SamplePoints', s.x_frag};

    % raw-fragment extrema (used for the 'мин Суммарного импульса' marker)
    sMinTF = islocalmin(s.sig_frag, ext{:});
    sMaxTF = islocalmax(s.sig_frag, ext{:});
    s.sig_x_min = s.x_frag(sMinTF);  s.sig_y_min = s.sig_frag(sMinTF);
    s.sig_x_max = s.x_frag(sMaxTF);  s.sig_y_max = s.sig_frag(sMaxTF);
    

    % polynomial fit on the fragment (mu = centring/scaling from polyfit)
    [s.p_coef, ~, s.mu] = polyfit(s.x_frag, s.sig_frag, polyDeg);
    polRaw = polyval(s.p_coef, s.x_frag, [], s.mu);
    s.polMaxRaw = max(polRaw);                 % scale kept for the continuous polFun
    if opts.Normalize
        pol = polRaw ./ s.polMaxRaw;
    else
        pol = polRaw;  s.polMaxRaw = 1;
    end
    s.pol = pol;

    % derivatives: numeric on the polynomial, plus the analytic polyder
    x_mid       = (s.x_frag(1:end-1) + s.x_frag(2:end)) / 2;
    s.diff1_pol = diff(s.pol)       ./ diff(s.x_frag);
    s.diff2_pol = diff(s.diff1_pol) ./ diff(x_mid);
    s.p_coef_d1 = polyder(s.p_coef);
    s.polyder   = polyval(s.p_coef_d1, s.x_frag, [], s.mu);

    % extrema of the polynomial: the two dominant maxima are the pulse peaks
    maxTF = islocalmax(s.pol, 'MaxNumExtrema', 2, 'SamplePoints', s.x_frag);
    s.x_max = s.x_frag(maxTF);  s.y_max = s.pol(maxTF);

    % ---- local minimum by bracketed minimisation between the two peaks ----
    % No amplitude cut. The valley is by definition the lowest point strictly
    % between the two peaks, so we minimise the continuous (normalised) poly on
    % the bracket [leftPeak, rightPeak]. fminbnd (Brent) is confined to the
    % bracket, so it can never run off to a fragment edge (Runge spikes), and a
    % missing second peak is reported as "no resolvable valley" (NaN) — that is
    % the resolution limit itself, not an error.
    polFun = @(xi) polyval(s.p_coef, xi, [], s.mu) ./ s.polMaxRaw;
    xPk = sort(s.x_max);
    if numel(xPk) >= 2
        [s.fzero_x, s.fzero_y] = fminbnd(polFun, xPk(1), xPk(end), ...
                                         optimset('TolX', 1e-6));
    else
        s.fzero_x = NaN;  s.fzero_y = NaN;   % single peak => pulses merged
    end

    % keep the old field names so report/plot/dither code is unchanged
    if isnan(s.fzero_x)
        s.x_min = [];          s.y_min = [];
    else
        s.x_min = s.fzero_x;   s.y_min = s.fzero_y;
    end
end

% ---------------------------------------------------------------------
%  Dithering: run analyzeSignal over nReal realizations and average the
%  scalar locations. Dither is Δ-referenced and drawn by makeDither with
%  the chosen PDF. If quantizeMain is true the dithered signal is passed
%  through the mid-tread quantizer (step Δ), so this is true non-subtractive
%  dithered quantization; otherwise the old "dither as additive noise" path.
%  Returns:
%    d.rep  - a representative single realization (curves for plotting)
%    d.mean - averaged locations,  d.std - spread across realizations
% ---------------------------------------------------------------------
function d = analyzeDithered(x, sumBase, mask, polyDeg, nReal, regen, ...
                             Delta, pdfType, quantizeMain, subtractive)
    if subtractive && ~quantizeMain
        error(['analyzeDithered: subtractive=true requires quantizeMain=true ' ...
               '(without a quantizer, subtracting d just cancels it exactly).']);
    end
    fragAccum = [];
    fzx = []; fzy = [];
    xmin = []; ymin = [];
    repS = struct();

    if ~regen
        dFixed = makeDither(pdfType, Delta, size(x));  % original fixed-dither mode
    end

    for kk = 1:nReal
        if regen
            rng(kk*17);                                % new realization each loop
            d_k = makeDither(pdfType, Delta, size(x));
        else
            d_k = dFixed;
        end

        sigIn = sumBase + d_k;
        if quantizeMain
            sigIn = quantize(sigIn, Delta);            % the quantizer the dither serves
            if subtractive
                sigIn = sigIn - d_k;   % receiver-side removal (Schuchman): total
            end                        % error q(v+d)−d−v ~ U(−Δ/2,Δ/2), signal-indep.
        end
        s = analyzeSignal(x, sigIn, mask, polyDeg);

        fragAccum = [fragAccum; s.sig_frag];                       %#ok<AGROW>
        if ~isempty(s.x_min)
            xmin(end+1) = s.x_min;    ymin(end+1) = s.y_min;       %#ok<AGROW>
            fzx(end+1)  = s.fzero_x;  fzy(end+1)  = s.fzero_y;     %#ok<AGROW>
        end
        repS = s;   % keep the last realization as the representative one
    end

    d.Delta = Delta;
    d.pdf   = pdfType;
    d.subtractive = subtractive;
    d.rep           = repS;
    d.n             = numel(fzx);     % realizations that yielded a detected minimum
    d.mean.sig_frag = mean(fragAccum, 1);
    d.mean.x_min    = mean(xmin);
    d.mean.y_min    = mean(ymin);
    d.mean.fzero_x  = mean(fzx);

    % Spread across realizations (sample std). Meaningful once dithRegen = true;
    % with the fixed-dither default every realization is identical, so std = 0.
    d.std.x_min   = std(xmin);
    d.std.y_min   = std(ymin);
    d.std.fzero_x = std(fzx);
    d.std.fzero_y = std(fzy);

    % Y at the averaged zero, read off the representative normalised polynomial
    if ~isempty(repS) && isfield(repS, 'pol')
        d.mean.fzero_y = interp1(repS.x_frag, repS.pol, d.mean.fzero_x, 'makima');
    else
        d.mean.fzero_y = NaN;
    end
end

% ---------------------------------------------------------------------
%  Console report for one impulse (all the fprintf, moved out of compute).
% ---------------------------------------------------------------------
function reportSignal(i_nImp, unn, noi, dit)
    fprintf('\n            -- ИМПУЛЬС %d. --\n', i_nImp);

    if i_nImp <= 7
        fprintf('\n Sum без шума.   x max Sum = %.7f   y max Sum = %.7f', ...
                scalarOrNaN(unn.sig_x_max), scalarOrNaN(unn.sig_y_max));
    else
        fprintf('\n Sum без шума.   x min Sum = %.7f   y min Sum = %.7f', ...
                scalarOrNaN(unn.sig_x_min), scalarOrNaN(unn.sig_y_min));
    end

    fprintf('\n медиана x_frag %d = %.7f\n', i_nImp, median(unn.x_frag));

    % --- polynomial minima (x) ---
    fprintf('\n    Минимум Pol   x min Pol без шум %d = %.7f', i_nImp, scalarOrNaN(unn.x_min));
    fprintf('\n     fzero        x min Pol без шум %d = %.7f', i_nImp, unn.fzero_x);
    fprintf('\n    Минимум Pol   x min Pol  +  шум %d = %.7f', i_nImp, scalarOrNaN(noi.x_min));
    fprintf('\n     fzero        x min Pol  +  шум %d = %.7f', i_nImp, noi.fzero_x);
    fprintf('\n    Минимум Pol   x min Pol  +  диз %d = %.7f ± %.7f', i_nImp, dit.mean.x_min, dit.std.x_min);
    fprintf('\n     fzero        x min Pol  +  диз %d = %.7f ± %.7f  (n=%d)\n', i_nImp, dit.mean.fzero_x, dit.std.fzero_x, dit.n);

    % --- polynomial minima (y) ---
    fprintf('\n    Минимум Pol   y min Pol без шум %d = %.7f', i_nImp, scalarOrNaN(unn.y_min));
    fprintf('\n     fzero        y min Pol без шум %d = %.7f', i_nImp, unn.fzero_y);
    fprintf('\n    Минимум Pol   y min Pol  +  шум %d = %.7f', i_nImp, scalarOrNaN(noi.y_min));
    fprintf('\n     fzero        y min Pol  +  шум %d = %.7f', i_nImp, noi.fzero_y);
    fprintf('\n    Минимум Pol   y min Pol  +  диз %d = %.7f ± %.7f', i_nImp, dit.mean.y_min, dit.std.y_min);
    fprintf('\n     fzero        y min Pol  +  диз %d = %.7f ± %.7f\n', i_nImp, dit.mean.fzero_y, dit.std.fzero_y);

    % --- polynomial maxima ---
    fprintf('\n    Максимум Pol.   x max Pol без шум %d = %.7f', i_nImp, scalarOrNaN(unn.x_max));
    fprintf('\n    Максимум Pol.   y max Pol без шум %d = %.7f\n', i_nImp, scalarOrNaN(unn.y_max));
    fprintf('\n    Максимум Pol.   x max Pol + шум %d = %.7f', i_nImp, scalarOrNaN(noi.x_max));
    fprintf('\n    Максимум Pol.   y max Pol + шум %d = %.7f\n', i_nImp, scalarOrNaN(noi.y_max));
    fprintf('\n    Максимум Pol.   x max Pol + диз %d = %.7f', i_nImp, scalarOrNaN(dit.rep.x_max));
    fprintf('\n    Максимум Pol.   y max Pol + диз %d = %.7f\n', i_nImp, scalarOrNaN(dit.rep.y_max));
end

% ---------------------------------------------------------------------
%  All plotting for one impulse (moved out of the main loop).
% ---------------------------------------------------------------------
function plotStep(i_nImp, x, sumUnn, unn, noi, dit)
    cSky = '#5abbe8';  cSky2 = '#4d9bbf';
    cOrn = '#FF8C00';  cOrn2 = '#FFB347';
    cVio = '#431e61';
    xf = unn.x_frag;

    figure('Name', sprintf('Шаг %d ', i_nImp));
    title(sprintf(' Шаг %d ', i_nImp));
    hold on; grid on;

    yline(0, '-k', 'LineWidth', 2);

    if i_nImp < 7
        if ~isempty(unn.x_min),     xline(unn.x_min,     '--k', 'LineWidth', 1); end
        if ~isempty(noi.x_min),     xline(noi.x_min,     '--k', 'LineWidth', 1); end
        if ~isempty(dit.rep.x_min), xline(dit.rep.x_min, '--k', 'LineWidth', 1); end
    else
        if ~isempty(unn.x_max),     xline(unn.x_max,     '--k', 'LineWidth', 1); end
    end

    % --- summed clean pulse + the three polynomials ---
    plot(x,  sumUnn,      'Color', cSky, 'LineWidth', 1,   'LineStyle', '--', 'DisplayName', sprintf('Импульс %d без шума', i_nImp));
    plot(xf, unn.pol,     'Color', cSky, 'LineWidth', 1.5, 'DisplayName', sprintf('Полином %d без шума', i_nImp));
    plot(xf, noi.pol,     'Color', 'r',  'LineWidth', 1.5, 'DisplayName', sprintf('Полином %d + шум', i_nImp));
    plot(xf, dit.rep.pol, 'Color', cVio, 'LineWidth', 1.5, 'DisplayName', sprintf('Полином %d + дизеринг', i_nImp));

    % --- extrema markers ---
    plot(unn.sig_x_min, unn.sig_y_min, 'bo', 'MarkerSize', 10, 'DisplayName', 'мин Суммарного импульса');
    plot(unn.x_min,     unn.y_min,     'k*', 'MarkerSize', 10, 'DisplayName', 'мин полинома');

    % --- fzero (exact polynomial minimum) markers on the curve ---
    plot(unn.fzero_x,      unn.fzero_y,      'bd', 'MarkerSize', 9, 'MarkerFaceColor', cSky, 'DisplayName', sprintf('мин Pol без шум %d', i_nImp));
    plot(noi.fzero_x,      noi.fzero_y,      'rd', 'MarkerSize', 9, 'MarkerFaceColor', 'r',  'DisplayName', sprintf('мин Pol + шум %d', i_nImp));
    plot(dit.mean.fzero_x, dit.mean.fzero_y, 'kd', 'MarkerSize', 9, 'MarkerFaceColor', 'k',  'DisplayName', sprintf('мин Pol + диз %d', i_nImp));

    % horizontal ± std bar on the dithered minimum (visible only when it spreads)
    if isfield(dit, 'std') && ~isnan(dit.std.fzero_x) && dit.std.fzero_x > 0
        errorbar(dit.mean.fzero_x, dit.mean.fzero_y, dit.std.fzero_x, 'horizontal', ...
                 'Color', 'k', 'LineWidth', 1, 'CapSize', 8, 'HandleVisibility', 'off');
    end

    % --- polynomial derivatives ---
    plot(xf(1:numel(unn.diff1_pol)),     unn.diff1_pol,     'Color', cSky,  'LineWidth', 1.5, 'LineStyle', '--', 'DisplayName', sprintf('diff 1 Pol без шум %d', i_nImp));
    plot(xf(1:numel(unn.diff2_pol)),     unn.diff2_pol,     'Color', cSky2, 'LineWidth', 1.5, 'LineStyle', '--', 'DisplayName', sprintf('diff 2 Pol без шум %d', i_nImp));
    plot(xf(1:numel(noi.diff1_pol)),     noi.diff1_pol,     'Color', cOrn,  'LineWidth', 1.5, 'LineStyle', '--', 'DisplayName', sprintf('diff 1 Pol + шум %d', i_nImp));
    plot(xf(1:numel(noi.diff2_pol)),     noi.diff2_pol,     'Color', cOrn2, 'LineWidth', 1.5, 'LineStyle', '--', 'DisplayName', sprintf('diff 2 Pol + шум %d', i_nImp));
    plot(xf(1:numel(dit.rep.diff1_pol)), dit.rep.diff1_pol, 'Color', cVio,  'LineWidth', 1.8, 'LineStyle', ':',  'DisplayName', sprintf('diff 1 Pol + диз %d', i_nImp));
    plot(xf(1:numel(dit.rep.diff2_pol)), dit.rep.diff2_pol, 'Color', cVio,  'LineWidth', 1.8, 'LineStyle', ':',  'DisplayName', sprintf('diff 2 Pol + диз %d', i_nImp));
    plot(xf(1:numel(dit.rep.polyder)),   dit.rep.polyder,   'Color', cVio,  'LineWidth', 1.8, 'LineStyle', ':',  'DisplayName', sprintf('polyder d1 диз %d', i_nImp));

    % --- markers where the 1st derivative crosses zero (placed on the d1 curve) ---
    yd1_unn = interpOnDeriv(xf, unn.diff1_pol,     unn.fzero_x);
    yd1_noi = interpOnDeriv(xf, noi.diff1_pol,     noi.fzero_x);
    yd1_dit = interpOnDeriv(xf, dit.rep.diff1_pol, dit.mean.fzero_x);
    plot(unn.fzero_x,      yd1_unn, 'b^', 'MarkerSize', 9, 'MarkerFaceColor', cSky, 'DisplayName', sprintf('d'' Pol без шум %d', i_nImp));
    plot(noi.fzero_x,      yd1_noi, 'r^', 'MarkerSize', 9, 'MarkerFaceColor', 'r',  'DisplayName', sprintf('d'' Pol + шум %d', i_nImp));
    plot(dit.mean.fzero_x, yd1_dit, 'k^', 'MarkerSize', 9, 'MarkerFaceColor', 'k',  'DisplayName', sprintf('d'' Pol + диз %d', i_nImp));

    if ~isempty(xf)
        xlim([min(xf), max(xf)]);
    end
    ylim([-max(unn.pol), 0.3 + max(unn.pol)]);
    hold off;
    % legend show   % <- uncomment to display the legend (DisplayNames are set)
end

% ---------------------------------------------------------------------
%  Small helpers
% ---------------------------------------------------------------------
function v = scalarOrNaN(a)
    % Return the first element, or NaN if the input is empty (so fprintf and
    % markers behave when islocalmin/islocalmax found nothing).
    if isempty(a)
        v = NaN;
    else
        v = a(1);
    end
end

function y = interpOnDeriv(xf, dvals, xq)
    % y-value on a derivative curve at query x, guarding empty / NaN inputs.
    xd = xf(1:numel(dvals));
    if isempty(xq) || any(isnan(xq)) || numel(xd) < 2
        y = NaN;
    else
        y = interp1(xd, dvals, xq, 'makima');
    end
end

% ---------------------------------------------------------------------
%  Dither-PDF linearisation-sweep functions
% ---------------------------------------------------------------------

% Uniform mid-tread quantizer with step Delta (the LSB).
function q = quantize(v, Delta)
    q = Delta * round(v / Delta);
end

% Canonical non-subtractive dither generators, referenced to the step Δ.
%  'rpdf'  : 1Δ p-p uniform, σ = Δ/√12  (mean-linearising only — Schuchman's
%            condition for SUBTRACTIVE dither; non-subtractively it leaves
%            noise modulation)
%  'tpdf'  : 2Δ p-p triangular, σ = Δ/√6  (sum of two uniforms; decouples
%            error mean AND variance from the signal at minimum added power —
%            Lipshitz/Wannamaker/Vanderkooy 1992)
%  'gauss' : σ = Δ/2 Gaussian (linearises all moments asymptotically; more
%            power than TPDF, unbounded tails)
function d = makeDither(pdfType, Delta, sz)
    switch lower(pdfType)
        case 'rpdf'
            d = Delta * (rand(sz) - 0.5);
        case 'tpdf'
            d = Delta * (rand(sz) + rand(sz) - 1);
        case 'gauss'
            d = (Delta/2) * randn(sz);
        otherwise
            error('makeDither: unknown pdfType "%s" (rpdf|tpdf|gauss)', pdfType);
    end
end

% Sweep dither RMS σ and measure the error in the recovered pulse position,
%  for all three dither PDFs at EQUAL RMS (the fair comparison: same added
%  power, different distribution shape).
%  For each pdf and σ: repeat M times { draw N independent dither rows of
%  RMS σ, add to the signal, quantize each, average, detect position }.
%  At σ = 0 only quantization bias remains; the dip at nonzero σ is the
%  linearisation optimum. Theory says the TPDF curve should flatten out
%  (signal-independent error) from σ = Δ/√6 onward, RPDF a bit earlier but
%  with residual modulation, Gaussian needing σ ≈ Δ/2.
function sw = sweepDitherPDF(x, sig, mask, params)
    Delta = params.quantFrac * max(sig);
    sigma = linspace(0, params.sweepSigmaMax * Delta, params.sweepNumSigma);
    pdfs  = {'rpdf', 'tpdf', 'gauss'};
    N = params.sweepNumAvg;
    M = params.sweepNumRepeat;
    L = numel(sig);

    % ground truth: position from the clean, un-quantized signal
    clean  = analyzeSignal(x, sig, mask, params.polyDeg);
    x_true = clean.fzero_x;

    % dim 1: pdf, dim 2: sigma, dim 3: mode (1 = non-subtractive, 2 = subtractive)
    rmse   = nan(numel(pdfs), params.sweepNumSigma, 2);
    bias   = nan(numel(pdfs), params.sweepNumSigma, 2);
    sd     = nan(numel(pdfs), params.sweepNumSigma, 2);
    validN = zeros(numel(pdfs), params.sweepNumSigma, 2);

    for mode = 1:2
        sub = (mode == 2);
        for ip = 1:numel(pdfs)
            for is = 1:params.sweepNumSigma
                s_rms = sigma(is);
                xhat = nan(1, M);
                for m = 1:M
                    dN = ditherWithStd(pdfs{ip}, s_rms, [N, L]); % N dither rows
                    qd = quantize(sig + dN, Delta);
                    if sub
                        qd = qd - dN;                 % subtractive recovery
                    end
                    rec = mean(qd, 1);                % average the N copies
                    s   = analyzeSignal(x, rec, mask, params.polyDeg);
                    xhat(m) = s.fzero_x;
                end
                good = xhat(isfinite(xhat));
                validN(ip, is, mode) = numel(good);
                if ~isempty(good)
                    err                = good - x_true;
                    rmse(ip, is, mode) = sqrt(mean(err.^2));
                    bias(ip, is, mode) = mean(err);
                    sd(ip, is, mode)   = std(good);
                end
            end
        end
    end

    sw.sigma  = sigma;   sw.Delta  = Delta;   sw.x_true = x_true;
    sw.pdfs   = pdfs;
    sw.modes  = {'non-subtractive', 'subtractive'};
    sw.rmse   = rmse;    sw.bias   = bias;    sw.sd     = sd;
    sw.validN = validN;
    % canonical operating points (σ of the standard form of each PDF);
    % row 1: non-subtractive (RPDF only mean-linearises there), row 2:
    % subtractive optimum is RPDF 1Δ — Schuchman's condition.
    sw.sigmaCanon = Delta * [1/sqrt(12), 1/sqrt(6), 1/2];
end

% Draw dither of a given PDF scaled to an exact RMS (std) value.
%  rpdf : uniform width w,            std = w/√12  → w = σ√12
%  tpdf : two uniforms of width w,    std = w/√6   → w = σ√6
%  gauss: σ·randn
function d = ditherWithStd(pdfType, sigmaRMS, sz)
    switch lower(pdfType)
        case 'rpdf',  d = sigmaRMS * sqrt(12) * (rand(sz) - 0.5);
        case 'tpdf',  d = sigmaRMS * sqrt(6)  * (rand(sz) + rand(sz) - 1);
        case 'gauss', d = sigmaRMS * randn(sz);
        otherwise,    error('ditherWithStd: unknown pdfType "%s"', pdfType);
    end
end

% Plot the linearisation curves (RMSE vs σ/Δ) for the three dither PDFs in
% both modes: solid = non-subtractive, dashed = subtractive. Stars mark each
% PDF's canonical non-subtractive point; the square marks Schuchman's
% subtractive optimum (RPDF, σ = Δ/√12).
function plotDitherSweep(sw, iSweep)
    figure('Name', sprintf('Dither PDF comparison — impulse %d', iSweep));
    cols = {'#d62728', '#431e61', '#5abbe8'};       % rpdf, tpdf, gauss
    sty  = {'-', '--'};                              % non-subtractive, subtractive
    hold on; grid on;
    for mode = 1:2
        for ip = 1:numel(sw.pdfs)
            plot(sw.sigma / sw.Delta, sw.rmse(ip, :, mode), sty{mode}, ...
                 'Color', cols{ip}, 'LineWidth', 1.5, 'Marker', 'o', ...
                 'MarkerSize', 4, 'MarkerFaceColor', cols{ip}, ...
                 'DisplayName', sprintf('%s (%s)', upper(sw.pdfs{ip}), sw.modes{mode}));
        end
    end
    % canonical non-subtractive operating points
    for ip = 1:numel(sw.pdfs)
        sc = sw.sigmaCanon(ip);
        yc = interp1(sw.sigma, sw.rmse(ip, :, 1), sc, 'linear');
        plot(sc / sw.Delta, yc, 'p', 'MarkerSize', 14, 'Color', cols{ip}, ...
             'MarkerFaceColor', cols{ip}, 'HandleVisibility', 'off');
    end
    % Schuchman point: subtractive RPDF at σ = Δ/√12
    ySch = interp1(sw.sigma, sw.rmse(1, :, 2), sw.sigmaCanon(1), 'linear');
    plot(sw.sigmaCanon(1) / sw.Delta, ySch, 's', 'MarkerSize', 12, ...
         'Color', cols{1}, 'MarkerFaceColor', 'w', 'LineWidth', 1.5, ...
         'DisplayName', 'Schuchman optimum (RPDF 1\Delta, subtractive)');
    xlabel('dither RMS  \sigma / \Delta');
    ylabel('position RMSE');
    title(sprintf('Dither: PDF and mode comparison (impulse %d)', iSweep));
    legend('Location', 'best');
    hold off;
end

% Dither std to add so total perturbation reaches the canonical linearising
%  level σ* (e.g. TPDF's Δ/√6), counting measured ambient noise σ_n toward it:
%  σ_d = sqrt(σ*^2 - σ_n^2), clamped at 0 (no dither once σ_n ≥ σ*).
function sigma_d = ditherBudget(sigmaStar, sigmaMeas)
    sigma_d = sqrt(max(0, sigmaStar^2 - sigmaMeas^2));
end
